### ISSUE TITLE
tag names normal rather than bold?

### ISSUE THREAD

**Issue by agentfitz** [Siddley/Enhanced.HTML.CFML#1]
Dude, thank you for making these syntax highlighting schemes for Sublime Text. They are awesome.

Quick question. As I compare the code from Dreamweaver to Sublime Text now, I'm noticing they are very very similar, the only thing that doesn't sit as well with my eyes is the bolded tag names in Sublime Text vs. the unbolded tag names in Dreamweaver, which I prefer.

Do you know, is there a way to modify whether the tags are bold with sytax schemes like this, or is that not possible? Maybe it could be a setting or something?

Thanks again, these schemes are great!

**Comment by Siddley** [comment]
It's quite easy to modify if you wish...

Open the Sublime Text 2/Packages/Enhanced HTML & CFML/ folder and find the '*.tm' file you wish to modify.

Open it in Sublime Text.

Look for tags like `<key>fontStyle</key><string>bold</string>` and simply delete the word "bold"

That should do it for you.

**Comment by agentfitz** [comment]
You are the man sir! Easy as you said and worked perfectly. I really appreciate it.
