### ISSUE TITLE
SQL not couloring

### ISSUE THREAD

**Issue by DeivissonSedrez** [Siddley/Enhanced.HTML.CFML#10]
my sql´s scripts on <cfquery>..</cfquery> is not colouring, it is right? if yes, Intend to add this feature?

Thankyou, the project is great =D

**Comment by Siddley** [comment]
It colours fine in ST2, not sure about ST3. I am no longer maintaining this package. Please fork and fix yourself or check the other forks for fixes. https://github.com/Siddley/Enhanced.HTML.CFML/network
