### ISSUE TITLE
HTML code: Apache server-side command look just like comments

### ISSUE THREAD

**Issue by oakley808** [Siddley/Enhanced.HTML.CFML#2]
Apache server-side includes and commands are colored like HTML comments. It would be nice if they were slightly different. 

eg

**Comment by Siddley** [comment]
Hi, could you give me an example of the code to work with, I am not very familiar with Apache server side includes.

Thanks.

**Comment by oakley808** [comment]
Hi.
Of course.
Apache server code in html always starts with this:



Specific examples would be:





So it's almost the same as an html comment, but has the # sign.
Here's a much more detail description if you want.
http://httpd.apache.org/docs/2.2/howto/ssi.html

-Michael

**Comment by Siddley** [comment]
Ok, thanks for the examples and links... I'll try to get to it this weekend.

**Comment by Siddley** [comment]
Hi, I no longer have time to maintain this, please fork and fix if you wish.
