### ISSUE TITLE
Tables, forms, inputs not coloring

### ISSUE THREAD

**Issue by skabr** [Siddley/Enhanced.HTML.CFML#4]
Hi,

I just installed your package, but it`s not coloring the tags like you showed in the screenshots.

Is there a workaround for this?

thx

**Comment by Siddley** [comment]
Have you got the settings in ST correct? The colour scheme in preferences must be set correctly, and the syntax in the view menu must be set to enhancedHTML.

What version of ST are you using, I haven't heard of this problem before.

**Comment by skabr** [comment]
Sorry,

I found the error.

So sorry
