### ISSUE TITLE
CPU @ 100%

### ISSUE THREAD

**Issue by defmeta** [Siddley/Enhanced.HTML.CFML#8]
I have had to remove this package from sublime text 3 (running on a recent mac mini) as it consistently opens 8 - 12 processes which all demand 100% cpu.

It's a shame as I found it really useful.

**Comment by jlwbps** [comment]
I just had to do the same thing on a Windows 7 machine. The package seems to break the index process for GOTO. Hope there is a fix soon. :)

**Comment by Siddley** [comment]
I am no longer maintaining this package. It was built for ST2 so issues in ST3 are unknown. Please fork and fix it if you wish.
